apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockerwebapp
  template:
    metadata:
      labels:
        app: dockerwebapp
    spec:
      containers:
      - name: dockerwebapp
        image: seanbryson/dockerwebapp:latest
        ports:
        - containerPort: 3000

